apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shop-cart-pvc
  namespace: shop-cart-ns
  labels:
    app: shop-cart

spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
